# Generated by Django 4.1.3 on 2022-11-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrsrcmngr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
