# Generated by Django 4.1.3 on 2022-11-13 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_address', models.CharField(max_length=50)),
                ('ipv4', models.CharField(max_length=50)),
                ('mac', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=100)),
                ('ipv6', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('hostnames', models.CharField(max_length=400)),
                ('os_fingerprint', models.CharField(max_length=200)),
                ('tcpsequence', models.CharField(max_length=50)),
                ('ipsequence', models.CharField(max_length=50)),
                ('uptime', models.CharField(max_length=50)),
                ('lastboot', models.CharField(max_length=50)),
                ('distance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='scans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scanName', models.CharField(max_length=100)),
                ('status', models.SmallIntegerField()),
                ('parsed', models.BooleanField()),
                ('path_to_xml', models.CharField(max_length=500)),
                ('ScanTemplate', models.CharField(choices=[('-oX -vvv --stats-every 1s --top-ports 100 -T2', 'Pirmais variants'), ('-oX -vvv --stats-every 1s --top-ports 100 -T3', 'Otrais variants'), ('-oX -vvv --stats-every 1s --top-ports 100 -T4', 'Tresais variants')], max_length=80)),
                ('ScanSchedule', models.CharField(choices=[('h', 'Every hour'), ('d', 'Every day'), ('w', 'Every week')], max_length=2)),
                ('scanAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
