# Generated by Django 4.1.3 on 2022-11-13 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='changes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(blank=True, max_length=100, null=True)),
                ('cur_val', models.CharField(max_length=200)),
                ('prev_val', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=70, null=True)),
                ('prev_rep_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('prev_rep_id', models.IntegerField(blank=True, null=True)),
                ('started_int', models.IntegerField(blank=True, null=True)),
                ('endtime_int', models.IntegerField(blank=True, null=True)),
                ('started_str', models.CharField(blank=True, max_length=200, null=True)),
                ('endtime_str', models.CharField(blank=True, max_length=200, null=True)),
                ('version', models.CharField(blank=True, max_length=40, null=True)),
                ('scan_type', models.CharField(blank=True, max_length=80, null=True)),
                ('num_services', models.IntegerField(blank=True, null=True)),
                ('elapsed', models.IntegerField(blank=True, null=True)),
                ('hosts_up', models.IntegerField(blank=True, null=True)),
                ('hosts_down', models.IntegerField(blank=True, null=True)),
                ('hosts_total', models.IntegerField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=400, null=True)),
                ('full_cmndline', models.CharField(max_length=300)),
                ('path_to', models.CharField(blank=True, max_length=400, null=True)),
                ('is_consistent', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='resourcegroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('subnet', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('protocol', models.CharField(blank=True, max_length=50, null=True)),
                ('name_conc', models.CharField(blank=True, max_length=200, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_ttl', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(blank=True, max_length=150, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('banner', models.CharField(blank=True, max_length=400, null=True)),
                ('servicefp', models.CharField(blank=True, max_length=200, null=True)),
                ('tunnel', models.CharField(blank=True, max_length=100, null=True)),
                ('is_removed', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='services_added_removed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('prev_report_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.reports')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.services')),
            ],
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.RemoveField(
            model_name='scans',
            name='parsed',
        ),
        migrations.RemoveField(
            model_name='scans',
            name='path_to_xml',
        ),
        migrations.AddField(
            model_name='scans',
            name='params',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='hostnames',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='ipsequence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='ipv4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='ipv6',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='lastboot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='mac',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='os_fingerprint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='tcpsequence',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='uptime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scans',
            name='scanAuthor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scans',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='host_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.hosts'),
        ),
        migrations.AddField(
            model_name='services',
            name='reports_belonging_to',
            field=models.ManyToManyField(blank=True, to='website.reports'),
        ),
        migrations.AddField(
            model_name='reports',
            name='scan_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.scans'),
        ),
        migrations.AddField(
            model_name='reports',
            name='to_services',
            field=models.ManyToManyField(blank=True, through='website.services_added_removed', to='website.services'),
        ),
        migrations.AddField(
            model_name='changes',
            name='cur_report_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reports'),
        ),
        migrations.AddField(
            model_name='changes',
            name='host_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.hosts'),
        ),
        migrations.AddField(
            model_name='changes',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.services'),
        ),
        migrations.AddField(
            model_name='hosts',
            name='reports_belonging_to',
            field=models.ManyToManyField(blank=True, to='website.reports'),
        ),
        migrations.AddField(
            model_name='hosts',
            name='resourcegroup_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.resourcegroups'),
        ),
    ]
