# Generated by Django 4.1.3 on 2023-01-01 17:45

from django.db import migrations, models
import website.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcegroups',
            name='subnet',
            field=models.CharField(help_text='Only IPv4 addresses are supported. Indicate subnet in CIDR notation (e.g. 198.162.0.1/24) or IPv4 address list (comma separated)', max_length=200, unique=True, validators=[website.custom_validators.validate_ips_or_subnet], verbose_name='Subnet or IP list'),
        ),
    ]
