# Generated by Django 4.1.3 on 2022-11-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_changes_reports_resourcegroups_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scans',
            name='status',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
