# Generated by Django 4.1.3 on 2022-11-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_scans_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scans',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scans',
            name='last_executed',
            field=models.DateTimeField(null=True),
        ),
    ]
