# Generated by Django 4.1.3 on 2022-11-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_scans_active_scans_last_executed'),
    ]

    operations = [
        migrations.AddField(
            model_name='scans',
            name='next_execution_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scans',
            name='last_executed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
