# Generated by Django 4.1.3 on 2022-11-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_scans_next_execution_at_alter_scans_last_executed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scans',
            name='ScanSchedule',
            field=models.CharField(choices=[('hh', 'Every half hour'), ('h', 'Every hour'), ('d', 'Every day'), ('w', 'Every week')], max_length=2),
        ),
        migrations.AlterField(
            model_name='scans',
            name='next_execution_at',
            field=models.DateTimeField(null=True),
        ),
    ]
