# Generated by Django 4.1.3 on 2022-11-19 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_scans_scanschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scans',
            name='resourcegroups_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.resourcegroups'),
        ),
    ]
