# Generated by Django 4.1.3 on 2022-11-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_scans_resourcegroups_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scans',
            name='ScanTemplate',
            field=models.CharField(choices=[('-oX -vvv --stats-every 1s --top-ports 100 -T2', 'Pirmais variants'), ('-oX --stats-every 1s --top-ports 100 -T3', 'Otrais variants'), ('-oX --stats-every 1s --top-ports 100 -T4', 'Tresais variants')], max_length=80),
        ),
    ]
