# Generated by Django 4.1.3 on 2022-11-19 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_scans_scantemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='resourcegroups_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.resourcegroups'),
            preserve_default=False,
        ),
    ]
