# Generated by Django 4.1.3 on 2022-11-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_reports_resourcegroups_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
    ]
