# Generated by Django 4.1.3 on 2022-11-19 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_reports_is_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='port',
        ),
    ]
