# Generated by Django 4.1.3 on 2022-11-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_reports_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='parse_success',
            field=models.BooleanField(default=True),
        ),
    ]
