# Generated by Django 4.1.3 on 2022-11-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_reports_resourcegroups_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='full_cmndline',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
