# Generated by Django 4.1.3 on 2022-11-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_hosts_is_added_hosts_is_removed_services_is_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='reason_ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
