# Generated by Django 4.1.3 on 2022-11-20 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_services_reason_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='to_services',
            new_name='services_a_r',
        ),
        migrations.RenameField(
            model_name='services_added_removed',
            old_name='service_id',
            new_name='service',
        ),
        migrations.AddField(
            model_name='services_added_removed',
            name='cur_report',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.reports'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services_added_removed',
            name='prev_report_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_report', to='website.reports'),
        ),
    ]
