# Generated by Django 4.1.3 on 2022-11-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_rename_to_services_reports_services_a_r_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hosts_added_removed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('cur_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.reports')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.hosts')),
                ('prev_report_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_report_hosts', to='website.reports')),
            ],
        ),
        migrations.AddField(
            model_name='reports',
            name='hosts_a_r',
            field=models.ManyToManyField(blank=True, through='website.hosts_added_removed', to='website.hosts'),
        ),
    ]
