# Generated by Django 4.1.3 on 2022-11-23 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_hosts_added_removed_reports_hosts_a_r'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changes',
            old_name='cur_report_id',
            new_name='cur_report',
        ),
        migrations.RenameField(
            model_name='changes',
            old_name='host_id',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='changes',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='hosts',
            old_name='resourcegroup_id',
            new_name='resourcegroup',
        ),
        migrations.RenameField(
            model_name='hosts_added_removed',
            old_name='prev_report_id',
            new_name='prev_report',
        ),
        migrations.RenameField(
            model_name='reports',
            old_name='resourcegroups_id',
            new_name='resourcegroups',
        ),
        migrations.RenameField(
            model_name='reports',
            old_name='scan_id',
            new_name='scan',
        ),
        migrations.RenameField(
            model_name='scans',
            old_name='resourcegroups_id',
            new_name='resourcegroups',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='host_id',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='services_added_removed',
            old_name='prev_report_id',
            new_name='prev_report',
        ),
    ]
