# Generated by Django 4.1.3 on 2022-11-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_rename_cur_report_id_changes_cur_report_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changes',
            old_name='prev_rep_id',
            new_name='prev_rep',
        ),
        migrations.RenameField(
            model_name='reports',
            old_name='prev_rep_id',
            new_name='prev_rep',
        ),
        migrations.RenameField(
            model_name='scans',
            old_name='resourcegroups',
            new_name='resourcegroup',
        ),
    ]
