# Generated by Django 4.1.3 on 2022-11-23 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_rename_prev_rep_id_changes_prev_rep_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='resourcegroups',
            new_name='resourcegroup',
        ),
    ]
