# Generated by Django 4.1.3 on 2022-11-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_rename_resourcegroups_reports_resourcegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='scans',
            name='task_etc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scans',
            name='task_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scans',
            name='task_progress',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scans',
            name='task_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
