# Generated by Django 4.1.3 on 2022-12-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_scans_task_etc_scans_task_name_scans_task_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='cur_val',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
