# Generated by Django 4.1.3 on 2022-12-21 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_changes_cur_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcegroups',
            name='description',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resourcegroups',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resourcegroups',
            name='subnet',
            field=models.CharField(blank=True, help_text='Only IPv4 addresses are supported. Indicate subnet in CIDR notation (e.g. 198.162.0.1/24)', max_length=100, null=True, verbose_name='Subnet'),
        ),
        migrations.AlterField(
            model_name='scans',
            name='ScanSchedule',
            field=models.CharField(choices=[('hh', 'Every half hour'), ('h', 'Every hour'), ('d', 'Every day'), ('w', 'Every week')], help_text='Indicate here how often would you like the scan to run.', max_length=2, verbose_name='Scan Schedule'),
        ),
        migrations.AlterField(
            model_name='scans',
            name='ScanTemplate',
            field=models.CharField(choices=[('-oX -vvv --stats-every 1s --top-ports 100 -T2', 'Pirmais variants'), ('--stats-every 1s --top-ports 100 -T3', 'Otrais variants'), ('--stats-every 1s --top-ports 100 -T4', 'Tresais variants')], help_text='Indicate here the scan template you want to use. Free parameter entry is not supported yet.', max_length=80, verbose_name='Scan Template'),
        ),
        migrations.AlterField(
            model_name='scans',
            name='active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='scans',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of Creation'),
        ),
        migrations.AlterField(
            model_name='scans',
            name='last_executed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Executed at'),
        ),
        migrations.AlterField(
            model_name='scans',
            name='next_execution_at',
            field=models.DateTimeField(null=True, verbose_name='Next Execution at'),
        ),
        migrations.AlterField(
            model_name='scans',
            name='params',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Parameters'),
        ),
        migrations.AlterField(
            model_name='scans',
            name='scanName',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='scans',
            name='status',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='scans',
            name='task_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Task Name'),
        ),
        migrations.AlterField(
            model_name='scans',
            name='task_progress',
            field=models.FloatField(blank=True, null=True, verbose_name='Task Progress'),
        ),
        migrations.AlterField(
            model_name='scans',
            name='task_status',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Task Status'),
        ),
        migrations.AlterField(
            model_name='scans',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date of Modification'),
        ),
    ]
