# Generated by Django 4.1.3 on 2022-12-21 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_alter_scans_scantemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcegroups',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Group Name'),
        ),
    ]
