# Generated by Django 4.1.3 on 2022-12-21 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_alter_resourcegroups_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scans',
            name='resourcegroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.resourcegroups', verbose_name='Group Name'),
        ),
    ]
