# Generated by Django 4.1.3 on 2022-12-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_alter_scans_resourcegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scans',
            name='active',
            field=models.BooleanField(blank=True, null=True, verbose_name='Make Active'),
        ),
    ]
