# Generated by Django 4.1.3 on 2022-12-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_alter_scans_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcegroups',
            name='ip_addresses',
            field=models.TextField(blank=True, null=True, verbose_name='IP Addresses'),
        ),
    ]
