# Generated by Django 4.1.3 on 2022-12-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_hosts_description_hosts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='reports_belonging_to',
            field=models.ManyToManyField(blank=True, related_name='hosts', to='website.reports'),
        ),
    ]
