# Generated by Django 4.1.3 on 2022-12-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_alter_hosts_reports_belonging_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='standard',
            field=models.BooleanField(default=False),
        ),
    ]
