# Generated by Django 4.1.3 on 2022-12-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_reports_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scans',
            name='ScanTemplate',
            field=models.CharField(choices=[('-oX -vvv --stats-every 1s --top-ports 100 -T2', '-oX -vvv --stats-every 1s --top-ports 100 -T2'), ('--stats-every 1s --top-ports 100 -T3', '--stats-every 1s --top-ports 100 -T3'), ('--stats-every 1s --top-ports 100 -T4', '--stats-every 1s --top-ports 100 -T4'), ('-O -P0 -sTUV --top-ports 1000', '-O -P0 -sTUV --top-ports 1000')], help_text='Indicate here the scan template you want to use. Free parameter entry is not supported yet.', max_length=80, verbose_name='Scan Template'),
        ),
    ]
