# Generated by Django 4.1.3 on 2022-12-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_alter_scans_scantemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='changes',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
