# Generated by Django 4.1.3 on 2022-12-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_changes_dismissed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcegroups',
            name='subnet',
            field=models.CharField(blank=True, help_text='Only IPv4 addresses are supported. Indicate subnet in CIDR notation (e.g. 198.162.0.1/24) or IPv4 address list (comma separated)', max_length=100, null=True, verbose_name='Subnet or IP list'),
        ),
    ]
