# Generated by Django 4.1.3 on 2022-12-30 02:29

from django.db import migrations, models
import website.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_alter_resourcegroups_subnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcegroups',
            name='subnet',
            field=models.CharField(blank=True, help_text='Only IPv4 addresses are supported. Indicate subnet in CIDR notation (e.g. 198.162.0.1/24) or IPv4 address list (comma separated)', max_length=100, null=True, validators=[website.custom_validators.validate_ips_or_subnet], verbose_name='Subnet or IP list'),
        ),
    ]
