# Generated by Django 4.1.3 on 2022-12-31 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_remove_resourcegroups_ip_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services_added_removed',
            name='cur_report',
        ),
        migrations.RemoveField(
            model_name='services_added_removed',
            name='prev_report',
        ),
        migrations.RemoveField(
            model_name='services_added_removed',
            name='service',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='hosts_a_r',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='services_a_r',
        ),
        migrations.DeleteModel(
            name='hosts_added_removed',
        ),
        migrations.DeleteModel(
            name='services_added_removed',
        ),
    ]
