# Generated by Django 4.1.3 on 2022-12-31 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_remove_services_added_removed_cur_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='resourcegroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.resourcegroups'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='resourcegroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.resourcegroups'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='scan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.scans'),
        ),
        migrations.AlterField(
            model_name='scans',
            name='resourcegroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.resourcegroups', verbose_name='Group Name'),
        ),
    ]
